name: Update History Data

on:
  schedule:
    # Run on weekdays (Monday to Friday) at 10:00 UTC(18:00 UTC+8 Asia/Taipei)
    - cron: "0 10 * * 1-5"
  workflow_dispatch: # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: history-data # Ensure the history-data branch is checked out

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Step 4: Run the Python script
      - name: Run Python Script
        run: poetry run python main.py

      # Step 5: Check if there are any changes in the data folder
      - name: Check for Changes
        id: check_changes
        run: |
          if [ -z "$(git status --porcelain data/)" ]; then
            echo "No changes in data folder, skipping workflow."
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
            exit 0
          fi
          echo "HAS_CHANGES=true" >> $GITHUB_ENV

      # Step 6: Configure Git user information
      - name: Configure Git
        if: env.HAS_CHANGES == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 7: Commit the changes
      - name: Commit Changes
        if: env.HAS_CHANGES == 'true'
        run: |
          git add data/
          git commit -m "⚙ auto: Update data on $(date +'%Y-%m-%d %H:%M:%S')"

      # Step 8: Push the changes to the history-data branch
      - name: Push Changes
        if: env.HAS_CHANGES == 'true'
        run: git push origin history-data
